### ISSUE TITLE
Error when load a runbot with a previuos session 

### ISSUE THREAD

**Issue by luistorresm** [Vauxoo/runbot-addons#167]
For more information:

https://www.youtube.com/watch?v=d2V9PwNWyIY

**Comment by luistorresm** [comment]
FYI @moylop260

**Comment by luisg123v** [comment]
@moylop260 
After debugging this, I discovered the cause

When Runbot generates builds, it also generates a unique database name (e.g. `4093-10-0-d31d0b-all`). However, since we use MQT scripts to initialize databases, the db name is harcoded, and it's always `openerp_test` (you can check [this runbot](http://54247-11-0-591ebc.runbot.vauxoo.com/web/database/selector) or any other one to see it by yourself). Therefore, I think the solution could be one of the following:
1. Modify MQT scripts to make the db name not being harcoded to `openerp_template` but rely on an environment variable, and set that variable using the db name Runbot produces.
1. Harcode our Runbot to always use `openerp_test` as the db name.
1. Delete the db name parameter from our Runbot. After all, there is only one db per build.

What solution do you like the most?

**Comment by moylop260** [comment]
Option3 Change the URL of the button like as https://github.com/Vauxoo/runbot-addons/pull/152/files but this time we dont have method
Should be a change in the xml template
